import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { existsSync, mkdirSync, copyFileSync } from "fs";
import { join } from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Vault plugin directory for dev mode auto-copy
const vaultPluginDir = join(
  process.env.HOME || process.env.USERPROFILE,
  "Documents",
  "main",
  ".obsidian",
  "plugins",
  "tasklens"
);

const copyPlugin = {
  name: "copy-to-vault",
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length > 0) return;
      if (!existsSync(vaultPluginDir)) {
        mkdirSync(vaultPluginDir, { recursive: true });
      }
      copyFileSync("main.js", join(vaultPluginDir, "main.js"));
      copyFileSync("manifest.json", join(vaultPluginDir, "manifest.json"));
      copyFileSync("styles.css", join(vaultPluginDir, "styles.css"));
      console.log("Copied to vault plugin directory");
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  alias: {
    react: "preact/compat",
    "react-dom": "preact/compat",
  },
  plugins: prod ? [] : [copyPlugin],
  define: {
    "process.env.NODE_ENV": prod ? '"production"' : '"development"',
  },
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
