import { existsSync, mkdirSync, copyFileSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { defineConfig } from "vite-plus";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE+
if you want to view the source, please visit the github repository of this plugin
*/
`;

const vaultPluginDir = join(
  process.env.HOME || process.env.USERPROFILE || "",
  "Documents",
  "obsidian",
  "main",
  ".obsidian",
  "plugins",
  "tasklens",
);

function prependBanner() {
  return {
    name: "prepend-banner",
    closeBundle() {
      const content = readFileSync("main.js", "utf-8");
      if (!content.startsWith("/*")) {
        writeFileSync("main.js", banner + content);
      }
    },
  };
}

function copyToVaultPlugin() {
  return {
    name: "copy-to-vault",
    closeBundle() {
      if (!existsSync(vaultPluginDir)) mkdirSync(vaultPluginDir, { recursive: true });
      for (const f of ["main.js", "manifest.json", "styles.css"]) {
        copyFileSync(f, join(vaultPluginDir, f));
      }
      console.log("Copied to vault plugin directory");
    },
  };
}

const isDev = process.env.NODE_ENV !== "production";

export default defineConfig({
  build: {
    lib: {
      entry: "src/main.ts",
      formats: ["cjs"],
      fileName: () => "main.js",
    },
    outDir: ".",
    emptyOutDir: false,
    sourcemap: isDev ? "inline" : false,
    minify: !isDev,
    target: "es2018",
    rolldownOptions: {
      external: [
        "obsidian",
        "electron",
        /^@codemirror\//,
        /^@lezer\//,
        /^node:/,
        // Node.js built-in modules
        "assert",
        "buffer",
        "child_process",
        "cluster",
        "crypto",
        "dgram",
        "dns",
        "domain",
        "events",
        "fs",
        "http",
        "https",
        "module",
        "net",
        "os",
        "path",
        "perf_hooks",
        "process",
        "punycode",
        "querystring",
        "readline",
        "repl",
        "stream",
        "string_decoder",
        "sys",
        "timers",
        "tls",
        "tty",
        "url",
        "util",
        "v8",
        "vm",
        "wasi",
        "worker_threads",
        "zlib",
      ],
      output: {
        exports: "auto",
      },
    },
  },

  resolve: {
    alias: {
      react: "preact/compat",
      "react-dom": "preact/compat",
    },
  },

  define: {
    "process.env.NODE_ENV": JSON.stringify(isDev ? "development" : "production"),
  },

  // テスト (vitest.config.ts を統合)
  test: {
    environment: "node",
    include: ["src/**/*.test.ts"],
  },

  // リント (oxlintrc.json + biome linter を統合)
  lint: {
    rules: {
      "typescript/no-explicit-any": "error",
    },
  },

  // フォーマット (biome.json formatter を統合)
  fmt: {
    semi: true,
    singleQuote: false,
    tabWidth: 2,
    useTabs: false,
    printWidth: 120,
  },

  // プリコミットフック (lefthook.yml を統合)
  staged: {
    "*.{ts,tsx}": "vp check --fix",
  },

  plugins: isDev ? [prependBanner(), copyToVaultPlugin()] : [prependBanner()],
});
